name: ${APP_NAME}-${STAGE}

services:

  traefik:
    image: traefik:v3.6.2
    profiles: [ "dev", "test","stage" ]
    container_name: traefik
    restart: always
    command:
      - --api=true
      - --api.dashboard=true
      - --log.level=DEBUG
      - --log.filePath=/logs/traefik.log
      - --entrypoints.web.address=:${TRAEFIK_WEB_PORT}
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true

    networks:
      - web
    ports:
      - "${TRAEFIK_WEB_PORT}:${TRAEFIK_WEB_PORT}"

    volumes:

      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs:/logs

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.service=api@internal"


  postgres:
    image: postgres:${POSTGRES_TAG:-17}
    profiles: [ "dev", "test","stage" ]
    container_name: postgres-${STAGE}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_INTERNAL_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - backend
      - web

  flyway:
    image: flyway/flyway:10
    profiles: [ "test", "stage" ]
    container_name: flyway-${STAGE}
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:${POSTGRES_INTERNAL_PORT}/${POSTGRES_DB}
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_CONNECT_RETRIES=10
    volumes:
      - ./flyway/sql:/flyway/sql:ro
    command: -locations=filesystem:/flyway/sql migrate
    networks:
      - backend

  flyway-dev:
    image: flyway/flyway:10
    profiles: [ "dev" ]
    container_name: flyway-dev-${STAGE}
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:${POSTGRES_INTERNAL_PORT}/${POSTGRES_DB}
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_CONNECT_RETRIES=10
    volumes:
      - ./flyway/sql:/flyway/sql:ro
      - ./flyway/sql/dev:/flyway/sql/dev:ro
    command: -locations=filesystem:/flyway/sql,filesystem:/flyway/sql/dev migrate
    networks:
      - backend

  dozzle:
    image: ghcr.io/amir20/dozzle:latest
    profiles: [ "dev", "test", "stage" ]
    container_name: dozzle-${STAGE}
    ports:
      - "${DOZZLE_PORT}:${DOZZLE_INTERNAL_PORT}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DOZZLE_LEVEL: info
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`${DOZZLE_HOST}`)"
      - "traefik.http.routers.dozzle.entrypoints=web"
      - "traefik.http.services.dozzle.loadbalancer.server.port=${DOZZLE_INTERNAL_PORT}"
      - "traefik.http.middlewares.dozzle-stripprefix.stripprefix.prefixes=/logs"
      - "traefik.http.routers.dozzle.middlewares=dozzle-stripprefix"

  minio:
    image: minio/minio:${MINIO_TAG}
    profiles: [ "dev", "test", "stage" ]
    container_name: minio-${STAGE}
    command: server /data --console-address ":${MINIO_CONSOLE_INTERNAL_PORT}"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

      # Optional: Standard-Bucket-Auto-Create via entrypoint/initjob
    ports:
      - "${MINIO_PORT:-9000}:${MINIO_INTERNAL_PORT}"
      - "${MINIO_CONSOLE_PORT:-9001}:${MINIO_CONSOLE_INTERNAL_PORT}"
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:${MINIO_INTERNAL_PORT}/minio/health/live || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev
    restart: unless-stopped
    networks:
      - backend
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      # MinIO Console (auf separatem Host minio.localhost)
      - "traefik.http.routers.minio-console.rule=Host(`${MINIO_CONSOLE_HOST}`)"
      - "traefik.http.routers.minio-console.entrypoints=web"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.services.minio-console.loadbalancer.server.port=${MINIO_CONSOLE_INTERNAL_PORT}"
      # MinIO API (auf separatem Host minio-api.localhost)
      - "traefik.http.routers.minio-api.rule=Host(`${MINIO_API_HOST}`)"
      - "traefik.http.routers.minio-api.entrypoints=web"
      - "traefik.http.routers.minio-api.service=minio-api"
      - "traefik.http.services.minio-api.loadbalancer.server.port=${MINIO_INTERNAL_PORT}"

  minio-init:
    image: minio/mc:latest
    profiles: [ "dev", "test", "stage" ]
    container_name: minio-init-${STAGE}
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_INTERNAL_PORT: ${MINIO_INTERNAL_PORT}
    volumes:
      - ./minio-init.sh:/init.sh:ro
      - ./static/file-1.txt:/data/file-1.txt:ro
      - ./static/file-2.txt:/data/file-2.txt:ro
      - ./static/file-3.txt:/data/file-3.txt:ro
    entrypoint: /bin/sh
    command: /init.sh
    restart: "no"
    networks:
      - backend


volumes:
  postgres_data:
  minio_data:

networks:
  web:
    external: true
  backend:
    internal: true